site_name: Build to Manage - Node.js Observability
repo_url: https://github.com/rafal-szypulka/b2m-nodejs-v2
site_url: https://rafal-szypulka.github.io/b2m-nodejs-v2/
nav:
    - 1. Introduction: index.md
    - 2. Node.js Logging: logging.md
    - 3. Node.js Monitoring: monitoring.md
    - 4. App monitoring on Openshift: OCP.md
    - 5. Distributed Tracing labs: "https://ibm-cloud-architecture.github.io/learning-distributed-tracing-101/docs/lab-jaeger-nodejs.html"
    - About: about.md
theme:
  name: 'material'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
