apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2m-nodejs
spec:
  selector:
    matchLabels:
      app: b2m-nodejs
  replicas: 1
  template:
    metadata:
      labels:
        app: b2m-nodejs
    spec:
      containers:
        - name: node-prom
          image: quay.io/garage_milan/b2m-nodejs
          ports:
            - containerPort: 3001
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 3
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: b2m-nodejs
  labels:
    name: b2m-nodejs
spec:
  ports:
    - port: 80
      name: web
      targetPort: 3001
      protocol: TCP
  selector:
    app: b2m-nodejs

