apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-monitor
    role: alert-rules
  name: prometheus-example-rules
  namespace: monitoring
spec:
  groups:
  - name: ./example.rules
    rules:
    - alert: ExampleAlert
      annotations:
        summary: High request latency
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[1m]))
        by (le, service, route, method)) > 0.08
      labels:
        severity: warning